version: '3'

services:  
  coffee:
    image: lalyos/12factor:edge
    # pull_policy: always
    environment:
      - TITLE=Kávészünet at Leadventures [${ENV:-Dev}]
      - COLOR=${COLOR:-lightgreen}
    ports:
      - 8888:80
    labels:
      - "traefik.frontend.rule=Host:coffee.${DOMAIN:-lvh.me}"
    
networks:
  default:
    external:
      name: traefik
