version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: always
    command:
      - --retry
      - --rest
      - --docker.domain=${DOMAIN:-lvh.me}
      - --docker.network=traefik
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN:-lvh.me}"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  default:
    external:
      name: traefik